name: release

on:
  create:
    tags: ['v*']
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'

      - name: create crypto.py
        run: echo "${{ secrets.CRYPTOPY }}" > WOTSTAT/res/scripts/client/gui/mods/wot_stat/common/crypto.py
        shell: bash

      - name: mod name
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          MOD=mod.wotStat_$VERSION.wotmod
          echo Version: $VERSION
          echo Mod name: $MOD
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MOD=$MOD" >> $GITHUB_ENV

      - name: build
        run: cd WOTSTAT && ./build.sh -v $VERSION && echo Mod name $MOD
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOD }}
          path: WOTSTAT/${{ env.MOD }}

      - name: upload linux artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: WOTSTAT/${{ env.MOD }}
          token: ${{ github.token }}
          body: |


            ----------------------
            `canary_upgrade=0.0`
